DECLARE @PROCSTART DATETIME = GETDATE();

----Procedure Here

DECLARE @PROCEND DATETIME = GETDATE();

INSERT INTO ProcedureLog
SELECT DB_NAME()
	,OBJECT_SCHEMA_NAME(@@PROCID)
	,OBJECT_NAME(@@PROCID)
	,SYSTEM_USER
	,CONVERT(DATE,GETDATE())
	,CONVERT(VARCHAR(5),CAST(@PROCSTART AS TIME),108)
	,CONVERT(VARCHAR(5),CAST(@PROCEND AS TIME),108)
	,DATEDIFF(MINUTE, @PROCSTART, @PROCEND)
